<?php

return [
    7 => '{"customer":{"full_name":"Postman Public Customer","nationality":"Moroccan","phone":"+212600000000","email":"postman.public@example.com","passport_or_cin":"PM123456","driving_license_number":"PM-DL-001"},"vehicle_id":{{public_vehicle_id}},"pickup_location_id":{{pickup_location_id}},"dropoff_location_id":{{dropoff_location_id}},"start_datetime":"2026-12-01 10:00:00","end_datetime":"2026-12-05 10:00:00","customer_notes":"Airport pickup please."}',
    8 => '{"vehicle_id":{{public_vehicle_id}},"start_datetime":"2026-12-01 10:00:00","end_datetime":"2026-12-05 10:00:00"}',
    9 => '{"email":"{{admin_email}}","password":"{{admin_password}}"}',
    17 => '{"name":"QA Disposable Brand {{qa_suffix}}","slug":"qa-disposable-brand-{{qa_suffix}}","is_active":true}',
    19 => '{"name":"QA Disposable Brand Updated","slug":"qa-disposable-brand-{{qa_suffix}}","is_active":true}',
    20 => '{"is_active":false}',
    23 => '{"name":"QA Disposable Category {{qa_suffix}}","slug":"qa-disposable-category-{{qa_suffix}}","description":"Disposable QA category.","is_active":true}',
    25 => '{"name":"QA Disposable Category Updated","slug":"qa-disposable-category-{{qa_suffix}}","description":"Updated disposable QA category.","is_active":true}',
    26 => '{"is_active":false}',
    29 => '{"brand_id":{{vehicle_brand_id}},"category_id":{{vehicle_category_id}},"status_slug":"available","transmission_type_slug":"manual","fuel_type_slug":"diesel","name":"QA Disposable Vehicle {{qa_suffix}}","slug":"qa-disposable-vehicle-{{qa_suffix}}","model":"Sandero","year":2024,"plate_number":"QA-{{qa_suffix}}","mileage":10000,"current_mileage_updated_at":"2026-06-10 10:00:00","seats":5,"doors":5,"daily_price":350,"weekly_price":2200,"monthly_price":8500,"deposit_amount":3000,"description":"Disposable QA vehicle.","is_featured":false,"is_active":true}',
    31 => '{"brand_id":{{vehicle_brand_id}},"category_id":{{vehicle_category_id}},"status_slug":"available","transmission_type_slug":"manual","fuel_type_slug":"diesel","name":"Postman Test Vehicle Updated","slug":"postman-test-vehicle","model":"Sandero","year":2024,"plate_number":"PM-100-TEST","mileage":13000,"seats":5,"doors":5,"daily_price":375,"weekly_price":2300,"monthly_price":8800,"deposit_amount":3000,"is_featured":false,"is_active":true}',
    32 => '{"status_slug":"maintenance","mileage":13500,"daily_price":390}',
    37 => '{"full_name":"QA Disposable Customer {{qa_suffix}}","nationality":"Moroccan","phone":"+212622222222","email":"qa.disposable.{{qa_suffix}}@example.com","passport_or_cin":"QA{{qa_suffix}}","driving_license_number":"QA-DL-{{qa_suffix}}"}',
    39 => '{"full_name":"QA Disposable Customer Updated","nationality":"Moroccan","phone":"+212622222222","email":"qa.disposable.{{qa_suffix}}@example.com","passport_or_cin":"QA{{qa_suffix}}","driving_license_number":"QA-DL-{{qa_suffix}}"}',
    40 => '{"phone":"+212633333333"}',
    45 => '{"location_type_slug":"agency","name":"QA Disposable Location {{qa_suffix}}","slug":"qa-disposable-location-{{qa_suffix}}","address":"QA Street, Dakhla","delivery_fee":50,"is_active":true}',
    47 => '{"location_type_slug":"agency","name":"QA Disposable Location Updated","slug":"qa-disposable-location-{{qa_suffix}}","address":"Updated QA Street, Dakhla","delivery_fee":75,"is_active":true}',
    48 => '{"delivery_fee":80,"is_active":false}',
    51 => '{"customer_id":{{customer_id}},"vehicle_id":{{vehicle_id}},"pickup_location_id":{{location_id}},"dropoff_location_id":{{location_id}},"start_datetime":"2026-11-01 10:00:00","end_datetime":"2026-11-05 10:00:00","customer_notes":"Postman admin reservation.","admin_notes":"QA disposable reservation."}',
    52 => '{"vehicle_id":{{vehicle_id}},"start_datetime":"2026-11-01 10:00:00","end_datetime":"2026-11-05 10:00:00","ignore_reservation_id":null}',
    55 => '{"customer_id":{{customer_id}},"vehicle_id":{{vehicle_id}},"pickup_location_id":{{location_id}},"dropoff_location_id":{{location_id}},"start_datetime":"2026-11-02 10:00:00","end_datetime":"2026-11-06 10:00:00","admin_notes":"Postman updated reservation notes."}',
    56 => '{"admin_notes":"Partial update from Postman."}',
    65 => '{"reservation_id":{{reservation_payment_id}},"payment_method_slug":"cash","payment_type_slug":"rental_payment","payment_status_slug":"paid","amount":300,"payment_date":"2026-06-10","paid_by_customer_name":"Postman Customer","reference":"PM-PAY-{{qa_suffix}}","notes":"Postman payment."}',
    67 => '{"reservation_id":{{reservation_payment_id}},"payment_method_slug":"cash","payment_type_slug":"rental_payment","payment_status_slug":"paid","amount":1000,"payment_date":"2026-06-10","reference":"PM-PAY-FULL-{{qa_suffix}}"}',
    68 => '{"payment_status_slug":"refunded","notes":"Refunded from Postman"}',
    76 => '{"vehicle_id":{{vehicle_id}},"maintenance_type_slug":"oil_change","maintenance_date":"2026-06-10","next_maintenance_date":"2026-07-10","mileage":21000,"cost":450,"garage_name":"Postman Garage","notes":"Postman maintenance.","vehicle_status_slug":"maintenance","create_expense":true,"expense_category_slug":"maintenance"}',
    79 => '{"vehicle_id":{{vehicle_id}},"maintenance_type_slug":"inspection","maintenance_date":"2026-06-11","next_maintenance_date":"2026-08-11","mileage":21500,"cost":500,"garage_name":"Postman Garage Updated","notes":"Updated maintenance."}',
    80 => '{"cost":475,"notes":"Patched maintenance."}',
    86 => '{"vehicle_id":{{vehicle_id}},"expense_category_slug":"fuel","amount":250,"expense_date":"2026-06-10","description":"Postman expense updated."}',
    87 => '{"expense_category_slug":"maintenance","amount":275}',
    83 => '{"vehicle_id":{{vehicle_id}},"expense_category_slug":"fuel","amount":200,"expense_date":"2026-06-10","description":"Postman fuel expense."}',
    91 => '{"vehicle_id":{{vehicle_id}},"alert_type_slug":"maintenance_due","title":"Postman Maintenance Alert {{qa_suffix}}","message":"Postman alert message.","due_date":"2026-12-01"}',
];
